openapi: 3.0.0

info:
  version: 0.0.1
  title: Connections
  description: The posts service

tags:
  - name: Connections
  - name: Users
paths:

  /users:
    get:
      summary: Find all users
      tags:
        - Users
      description: Find all users
      operationId: findAllUsers
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Add new user
      tags:
        - Users
      operationId: saveUser
      requestBody:
        required: true
        description: User obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string


  /users/{userId}:
    get:
      summary: Find user by userId
      tags:
        - Users
      operationId: getUserByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    put:
      summary: Update user by userId
      tags:
        - Users
      operationId: updateUserByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: User obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string

  /connections:
    get:
      summary: Get all connections
      operationId: getConnections
      tags:
        - Connections
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
    post:
      summary: Add new connection
      operationId: saveConnection
      tags:
        - Connections
      requestBody:
        required: true
        description: Connections obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string

  /connections/{userId}/follower:
    get:
      summary: Get follower by userId
      operationId: getFollowerConnectionByUserName
      tags:
        - Connections
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'

  /connections/{userId}/followed:
    get:
      summary: Get followed by userId
      operationId: getFollowedConnectionByUserName
      tags:
        - Connections
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'

  /connections/{userId}:
    put:
      summary: Update connection by userId
      tags:
        - Connections
      operationId: updateConnectionByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: Connection obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    User:
      type: object
      required:
        - uuid
        - name
        - surname
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: Ivan
        surname:
          type: string
          example: Drago

    Connection:
      type: object
      required:
        - uuid
        - follower
        - followed
      properties:
        uuid:
          type: string
          format: uuid
        follower:
          type: string
          format: uuid
        followed:
          type: string
          format: uuid
