openapi: 3.0.0

info:
  version: 0.0.1
  title: Posts
  description: The posts service

tags:
  - name: Posts

paths:

  /posts:
    get:
      summary: Find all users
      tags:
        - Posts
      description: Find posts
      operationId: findPosts
      parameters:
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      tags:
        - Pots
      operationId: savePost
      requestBody:
        required: true
        description: Post obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        "200":
          description: This means is ok
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Post:
      type: object
      required:
        - userId
        - title
        - date
        - body
      properties:
        userId:
          type: string
          format: uuid
        title:
          type: string
        date:
          type: string
          format: date
        body:
          type: string
          example: 'text about life'
