spring:
  main:
    banner-mode: "off"
  datasource:
    url: '@db.url@'
    username: '@db.username@'
    password: '@db.password@'
    driver-class-name: '@db.driver@'
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    version: '@revision@'
