management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    version: '@revision@'

endpoint:
  post:
    url: "http://192.168.0.110:30300"
  connection:
    url: "http://localhost:8090"
